name: atta_galatta
description: "my bookstore app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^1.0.6 
  flutter_html: ^2.2.1
  html: ^0.15.0
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_analytics: ^10.10.5
  font_awesome_flutter: ^10.1.0
  table_calendar: any
  url_launcher: ^6.0.13 
  http: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/lib3.png
    - assets/backarrow.png
    - assets/logo2.png
